name: ci-golang-worflow
on: 
  pull_request:
    branches: 
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.14', '1.15']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ natrix.go }}
      - run: go test
      - run: go run math.go